# Generated by Django 5.0.4 on 2024-05-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_npages_user_nprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npages',
            name='image',
            field=models.FileField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='nprofile',
            name='image',
            field=models.FileField(default='default.svg', upload_to='pics'),
        ),
    ]
