# Generated by Django 4.2.13 on 2024-06-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_nimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nprofile',
            name='image',
            field=models.FileField(blank=True, default='defualt/default.jpg', null=True, upload_to='pics'),
        ),
    ]
