# Generated by Django 4.2.13 on 2024-06-29 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0006_alter_nprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='npages',
            name='cholestrol_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='npages',
            name='cumulative_require',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='npages',
            name='cumulative_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='npages',
            name='metabolic_syndrome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='npages',
            name='pressure_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='npages',
            name='cumulative_glucose_test',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nprofile',
            name='usr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
