# Generated by Django 4.2.13 on 2024-07-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_npages_cholestrol_status_npages_cumulative_require_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nprofile',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
