# Generated by Django 4.2.13 on 2024-07-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_nprofile_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='npages',
            name='heart_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='npages',
            name='smoker_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
